# Generated by Django 5.1 on 2024-08-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0002_alter_person_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPallete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallete_name', models.CharField(max_length=30)),
                ('primary_color', models.CharField(max_length=30)),
                ('secondary_color', models.CharField(max_length=30)),
                ('contrast_color', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_images/'),
        ),
    ]
