# Generated by Django 5.1 on 2024-08-30 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0003_colorpallete_person_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pallete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color_pallete', to='cv_manager.colorpallete'),
        ),
    ]
