# Generated by Django 5.1 on 2024-08-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0004_person_pallete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('fas fa-envelope', 'Email'), ('fas fa-phone', 'Phone'), ('fas fa-map-marker-alt', 'Adress'), ('fab fa-github', 'Github'), ('fab fa-linkedin', 'Linkedin'), ('fab fa-facebook', 'Facebook'), ('fab fa-instagram', 'Instagram'), ('fab fa-twitter', 'Twitter'), ('fas fa-cogs', 'Other')], max_length=30),
        ),
    ]
