# Generated by Django 5.1 on 2024-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0005_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='laboralexp',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
